* schlau-compile                                                   :TOC_5_gh:
  - [[#synopsis][Synopsis]]
  - [[#author][Author]]
  - [[#version][Version]]
  - [[#acknowledgements][Acknowledgements]]
    - [[#llm-usage][LLM usage]]
  - [[#lisense][Lisense]]
  - [[#documentation][Documentation]]
    - [[#companion-project-emacs-config][Companion project: emacs-config]]
    - [[#configuring-your-own-macros-advanced-setup][Configuring your own macros, advanced setup]]
    - [[#string---macos][String %- Macos]]
    - [[#simple-setup-example-for-your-emacs-file][Simple setup example for your .emacs file]]
    - [[#workflow][Workflow]]
  - [[#recent-changes]["Recent" changes]]

** Synopsis
   A utility to allow you to configure
   compilation for any git project.

** Author
   Fred Mitchell

** Version   
   1.1.0

** Acknowledgements
   Forked from the original "Smart Compile" by Seiji Zenitani 
   at https://github.com/zenitani/elisp. To avoid namespace
   collisions, all symbols have been renamed. So, you can use
   both schlau-compile and smart-compile at the same time, 
   but then why would you want to? We've added features and changed
   the workflow that goes beyond  smart-compile.

   Contributers to the orginal smart-compile:
   Seiji Zenitani, Sakito Hisakura, and Greg Pfell

*** LLM usage
    I started on this project long before LLMs became the thing they are today.
    I did use an LLM to clean up the code a bit to get it ready for MELPA,
    but this project is largely hand-crearted

    Today I do make use of LLMs, but in a controlled fashion. I will have
    it create "bolier-plate" code for what I am working on, or spin example
    code for an API I am not yet familiar with. Think of using Stack Overflow
    on steroids.

    I see the seduction on relying on LLMs more heavily, but I like to keep 
    my own hands dirty. Should the VC funding for all these wonderous LLMs
    drop someday, I don't want to be caught with my nickers down! And I've
    been around to see many things come and go, and some of you may recall the 
    great Dot.Com crash of 2000. Oh, I was in the middle of that. Lessons learnt.

    I don't mean to be a doomsayer, but just a realist. The LLM bubble will eventually
    burst for "reasons" that are out of scope to discuss here. Feel free to PM
    me if you are interested in my opinions on the topic.

** Lisense
   The original code is covered by GPLv3. I was required by said license
   to place schlau-compile under the same license, though I normally put
   nearly all of my opensource work under MIT.

** Documentation
   schlau-compile -- the "schlau" part of the name is the German word for "smart".
   
   schlau-compile's best new feature is that it will look for the root of your
   git project to reference what needs to be compiled underneath. We have
   added macros that allows you to leverage that functionality. 

   So basically, the currently active buffer is referenced by its 
   major mode to find the compile string to run. Please see the provided 
   example below.
*** Companion project: emacs-config
    Please visit the [[https://github.com/flajann2/emacs-config][emacs-config]] project, which has numerous examples
    to support many different languages, especially [[https://github.com/flajann2/emacs-config/blob/master/init/schlau-ext.el][schlau-ext.el]].
    You may use the entirety of emacs-config, or "steal" the parts that
    you are most interested in. emacs-config has been in development for
    over a decade, and recently someone convinced me to make it all public.

    You will note that the snippet below comes from emacs-config, scaled back
    for illustrative purposes.
*** Configuring your own macros, advanced setup
    I provide an example, and it is actually the same one
    I used to use on a daily basis. Please see emacs-config for my
    current daily driver.

    #+begin_src elisp
(require 'compile)
(require 'schlau-compile)

(defconst cppninja "if [ ! -d %G/build ]; then mkdir %G/build; fi ; cd %G/build && echo \"Entering directory \'%G/build\'\" && cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_CODE_ANALYSIS=ON .. && ninja -k3 -j8")
(defconst cppmake  "if [ ! -d %G/build ]; then mkdir %G/build; fi ; cd %G/build && echo \"Entering directory \'%G/build\'\" && cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_CODE_ANALYSIS=ON .. && make")
(defconst rustmake "RUST_BACKTRACE=1 ~/.cargo/bin/cargo build && ~/.cargo/bin/cargo test -- --nocapture")
(defconst rubymake "rake build")
(defconst gomake  "export GOPATH=/development/go ; go install ./... && go test -v && go vet")
(defconst hackage "cd %G && stack build --allow-different-user && stack test")

(setq schlau-compile-alist
      (append
       ;; build Haskell
       (eval `'((haskell-mode  . ,hackage)))
       (eval `'((yaml-mode     . ,hackage)))

       ;; compile Go
       (eval `'((go-mode . ,gomake)))

       ;; compile C++
       (eval `'((c++-mode   . ,cppninja)))
       (eval `'((cmake-mode . ,cppninja)))

       ;; compile Rust
       (eval `'((rust-mode  . ,rustmake)))
       (eval `'((toml-mode  . ,rustmake)))

       ;; compile rubygem
       (eval `'((ruby-mode  . ,rubymake)))
       ))

(global-set-key [f5] 'schlau-compile-compile)
(global-set-key [f6] 'schlau-compile-query)
(global-set-key [C-f6] 'kill-compilation)
    #+end_src

    You will note that I have configured a few languages; C++ (using CMake,
    both make and ninja), Haskell, Rust, Ruby, and Go.

    Note that the actual compile macros are defined as defconsts,
    and that the actual schlau-compile-alist references defconst. We
    do it this way so that you can target multiple modes for compilation.
    Like, for example, C++ files and the CMake file that builds them,
    and in the case for Rust, the Rust source code and the Cargo.toml
    file that builds them. This is in keeping with the DRY principle.

    Hotkeys:
    + F5 will compile using either the default string as determined
      from the alist, or from your modified compile string you made from F6.
    + F6 provide you with the actual resolved macro compile string, first,
      allowing you to make temporary modifications to it before you compile. Subsequently,
      you can hit F5 to run the the modified compile string.
      
      Note that your F6 modifications will only persist during the life of the
      Emacs session and will not be permanent. Make any permanent modifications
      to the defconst macros in your configuration.
    
*** String %- Macos
     Alist of filename patterns vs corresponding format control strings.
     Each element looks like (REGEXP . STRING) or (MAJOR-MODE . STRING).
     Visiting a file whose name matches REGEXP specifies STRING as the
     format control string.  Instead of REGEXP, MAJOR-MODE can also be used.
     The compilation command will be generated from STRING.
     The following %-sequences will be replaced by:

     | Macro | Description                             | Example Results             |
     |-------+-----------------------------------------+-----------------------------|
     | %F    | absolute pathname                       | ~/your_project/src/main.cpp |
     | %f    | file name without directory             | main.cpp                    |
     | %n    | file name without extension             | main                        |
     | %e    | extension of file name                  | cpp                         |
     | %G    | root path of git project                | ~/your_project/             |
     | %o    | value of `schlau-compile-option-string' | "user-defined"              |

*** Simple setup example for your .emacs file
     Here we show a custom example of doing a cmake c++ project compile,
     and one for Rust as well. Note the use of %G in the case of cmake. Note
     as well that this is a simple example that does not use defconst.

     #+begin_src lisp
     (setq schlau-compile-alist
      (append
       ;; compile C++
       '((c++-mode . "cd %G && cmake . && make -k -j8"))

       ;; compile Rust
       '((rust-mode . "RUST_BACKTRACE=1 cargo build"))
       ))

     (global-set-key [F5] 'schlau-compile-compile)
     (global-set-key [f6] 'schlau-compile-query)
     (global-set-key [C-F6] 'kill-compilation)
     #+end_src

     And you will also note the last 3 lines setting up a key mapping,
     which you are of course free to change to your own liking.
*** Workflow
    + The current buffer's language type invokes the macro that is used to
      compile the entire project to which that buffer is a part. So, it is
      possible to support more than one language in a project, which you may
      need to do sometimes. For example, if you are doing a website, you may
      have Haskell (or some other language) running the back-end, and Elm
      (or TypeScript or PureScript) running the front-enb. If you are in 
      a buffer containing the Elm code, it will compile that. Or if you are
      in the Haskell buffer, it will compile that instead.
    + Of course, you can configure your macros to compile both languages
      when in Haskell and just Elm when you are in the Elm buffer. You
      have the full power to configure your own workflow.
    + Support for LLMs like Claude Code is not complete yet. I am open
      to pull requests should you wish.

** "Recent" changes
   I changed the way F5 and F6 keys work. You will always get a meaningful
   compile string, and F6 is now used to modify the string before the compilation,
   wheras before F5 did that (and F6 did not default to anything meaningful.)

   I made this change sometime back, so they are no longer "recent".
